<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SubProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $model = array(
            array('name' => 'HG23 Trắng Đen Nâng Cấp', 'real_price' => null, 'daily_price' => null, 'flash_sale_price' => null, 'stock_quantity' => 100, 'sold_quantity' => 100, 'product_id' => 1, 'image_url' => 'https://firebasestorage.googleapis.com/v0/b/hangy-storage.appspot.com/o/products%2Fhg23%2Fhg23-5.jpg?alt=media&token=1129d857-c244-4ca7-9338-0cf227574293', 'created_at' => now(), 'updated_at' => now()),
            array('name' => 'HG23 Đen Nâng Cấp', 'real_price' => null, 'daily_price' => null, 'flash_sale_price' => null, 'stock_quantity' => 100, 'sold_quantity' => 100, 'product_id' => 1, 'image_url' => 'https://firebasestorage.googleapis.com/v0/b/hangy-storage.appspot.com/o/products%2Fhg23%2Fhg23-6.jpg?alt=media&token=6e4cdd7b-18f7-4f76-8a7b-44006bd40951', 'created_at' => now(), 'updated_at' => now()),
            array('name' => 'HG23 Mix Nâng Cấp', 'real_price' => 1600000, 'daily_price' => 719000, 'flash_sale_price' => 700000, 'stock_quantity' => 100, 'sold_quantity' => 100, 'product_id' => 1, 'image_url' => 'https://firebasestorage.googleapis.com/v0/b/hangy-storage.appspot.com/o/products%2Fhg23%2Fhg23-2.jpg?alt=media&token=6be71efd-fb8a-4ea9-9f60-f7394853b127', 'created_at' => now(), 'updated_at' => now()),
            array('name' => 'HM23 Trắng Nâng Cấp', 'real_price' => null, 'daily_price' => null, 'flash_sale_price' => null, 'stock_quantity' => 100, 'sold_quantity' => 100, 'product_id' => 2, 'image_url' => 'https://firebasestorage.googleapis.com/v0/b/hangy-storage.appspot.com/o/products%2Fhm23%2Fhm23-4.png?alt=media&token=a568fa5e-fb7b-4c2d-be4f-f8a04507cc93', 'created_at' => now(), 'updated_at' => now()),
            array('name' => 'HG23 Đen Nâng Cấp', 'real_price' => null, 'daily_price' => null, 'flash_sale_price' => null, 'stock_quantity' => 100, 'sold_quantity' => 100, 'product_id' => 2, 'image_url' => 'https://firebasestorage.googleapis.com/v0/b/hangy-storage.appspot.com/o/products%2Fhm23%2Fhm23-14.jpg?alt=media&token=60feb325-22f4-443b-b7ea-36c2830ea360', 'created_at' => now(), 'updated_at' => now()),
            array('name' => 'HG23 Xanh Mint Nâng Cấp', 'real_price' => null, 'daily_price' => null, 'flash_sale_price' => null, 'stock_quantity' => 100, 'sold_quantity' => 100, 'product_id' => 2, 'image_url' => 'https://firebasestorage.googleapis.com/v0/b/hangy-storage.appspot.com/o/products%2Fhm23%2Fhm23-4.png?alt=media&token=a568fa5e-fb7b-4c2d-be4f-f8a04507cc93', 'created_at' => now(), 'updated_at' => now()),
            array('name' => 'H1 Trắng Nâng Cấp', 'real_price' => null, 'daily_price' => null, 'flash_sale_price' => null, 'stock_quantity' => 100, 'sold_quantity' => 100, 'product_id' => 3, 'image_url' => 'https://firebasestorage.googleapis.com/v0/b/hangy-storage.appspot.com/o/products%2Fh1%2Fh1-11.jpg?alt=media&token=ad74550f-d510-4f9f-996e-e99fcd313894', 'created_at' => now(), 'updated_at' => now()),
            array('name' => 'H1 Đen Nâng Cấp', 'real_price' => null, 'daily_price' => null, 'flash_sale_price' => null, 'stock_quantity' => 100, 'sold_quantity' => 100, 'product_id' => 3, 'image_url' => 'https://firebasestorage.googleapis.com/v0/b/hangy-storage.appspot.com/o/products%2Fh1%2Fh1-1.jpg?alt=media&token=8730ef7c-117b-4b78-b0dc-82cb748600b3', 'created_at' => now(), 'updated_at' => now()),
            array('name' => 'H1 Hồng Nâng Cấp', 'real_price' => null, 'daily_price' => null, 'flash_sale_price' => null, 'stock_quantity' => 100, 'sold_quantity' => 100, 'product_id' => 3, 'image_url' => 'https://firebasestorage.googleapis.com/v0/b/hangy-storage.appspot.com/o/products%2Fh1%2Fh1-2.jpg?alt=media&token=ef8e3306-cdfe-4c1e-b38c-f2dba158ba64', 'created_at' => now(), 'updated_at' => now()),
            array('name' => 'HY23 Pro Trắng Nâng Cấp', 'real_price' => null, 'daily_price' => null, 'flash_sale_price' => null, 'stock_quantity' => 100, 'sold_quantity' => 100, 'product_id' => 4, 'image_url' => 'https://firebasestorage.googleapis.com/v0/b/hangy-storage.appspot.com/o/products%2Fhy23-pro%2Fhy23pro-1.jpg?alt=media&token=3977ab46-ec7f-445b-84aa-de9386f2ef8f', 'created_at' => now(), 'updated_at' => now()),
            array('name' => 'HY23 Pro Đen Nâng Cấp', 'real_price' => null, 'daily_price' => null, 'flash_sale_price' => null, 'stock_quantity' => 100, 'sold_quantity' => 100, 'product_id' => 4, 'image_url' => 'https://firebasestorage.googleapis.com/v0/b/hangy-storage.appspot.com/o/products%2Fhy23-pro%2Fhy23pro-2.jpg?alt=media&token=c4e2e09e-0394-49ae-8f29-148c74273a2c', 'created_at' => now(), 'updated_at' => now()),
            array('name' => 'HY23 Pro Hồng Nâng Cấp', 'real_price' => null, 'daily_price' => null, 'flash_sale_price' => null, 'stock_quantity' => 100, 'sold_quantity' => 100, 'product_id' => 4, 'image_url' => 'https://firebasestorage.googleapis.com/v0/b/hangy-storage.appspot.com/o/products%2Fhy23-pro%2Fhy23pro-3.jpg?alt=media&token=9e93d953-d38c-49d5-8064-e81df65a056d', 'created_at' => now(), 'updated_at' => now()),
            array('name' => 'HY23 Pro Xanh Nâng Cấp', 'real_price' => null, 'daily_price' => null, 'flash_sale_price' => null, 'stock_quantity' => 100, 'sold_quantity' => 100, 'product_id' => 4, 'image_url' => 'https://firebasestorage.googleapis.com/v0/b/hangy-storage.appspot.com/o/products%2Fhy23-pro%2Fhy23pro-4.jpg?alt=media&token=8d5641f6-7958-44fc-b9ce-143e17b55c20', 'created_at' => now(), 'updated_at' => now()),
            array('name' => 'HY23 Trẻ em Vàng Nâng Cấp', 'real_price' => null, 'daily_price' => null, 'flash_sale_price' => null, 'stock_quantity' => 100, 'sold_quantity' => 100, 'product_id' => 5, 'image_url' => 'https://firebasestorage.googleapis.com/v0/b/hangy-storage.appspot.com/o/products%2Fhy23-TE%2Fhy23te-2.jpg?alt=media&token=211e1227-9b44-411e-b1a1-473c1da94c7a', 'created_at' => now(), 'updated_at' => now()),
            array('name' => 'HY23 Trẻ em Xanh Nâng Cấp', 'real_price' => null, 'daily_price' => null, 'flash_sale_price' => null, 'stock_quantity' => 100, 'sold_quantity' => 100, 'product_id' => 5, 'image_url' => 'https://firebasestorage.googleapis.com/v0/b/hangy-storage.appspot.com/o/products%2Fhy23-TE%2Fhy23te-1.jpg?alt=media&token=460ce856-01eb-4378-888c-d0dd2eadead2', 'created_at' => now(), 'updated_at' => now()),
            array('name' => 'HY23 Trẻ em Hồng Nâng Cấp', 'real_price' => null, 'daily_price' => null, 'flash_sale_price' => null, 'stock_quantity' => 100, 'sold_quantity' => 100, 'product_id' => 5, 'image_url' => 'https://firebasestorage.googleapis.com/v0/b/hangy-storage.appspot.com/o/products%2Fhy23-TE%2Fhy23te-5.jpg?alt=media&token=d684b4ad-6f81-4d5c-b86a-56522c761cc2', 'created_at' => now(), 'updated_at' => now()),
            array('name' => 'HY23 Ultra Trắng Nâng Cấp', 'real_price' => null, 'daily_price' => null, 'flash_sale_price' => null, 'stock_quantity' => 100, 'sold_quantity' => 100, 'product_id' => 6, 'image_url' => 'https://firebasestorage.googleapis.com/v0/b/hangy-storage.appspot.com/o/products%2Fhy23-ultra%2Fhy23ultra-2.jpg?alt=media&token=ae339ec7-2a29-4540-9ef5-bb0a50fdb9db', 'created_at' => now(), 'updated_at' => now()),
            array('name' => 'HY23 Ultra Đen Nâng Cấp', 'real_price' => null, 'daily_price' => null, 'flash_sale_price' => null, 'stock_quantity' => 100, 'sold_quantity' => 100, 'product_id' => 6, 'image_url' => 'https://firebasestorage.googleapis.com/v0/b/hangy-storage.appspot.com/o/products%2Fhy23-ultra%2Fhy23ultra-1.jpg?alt=media&token=13f553d7-681c-4358-8879-1f77bedb8b05', 'created_at' => now(), 'updated_at' => now()),
            array('name' => 'Vị Đào', 'real_price' => null, 'daily_price' => null, 'flash_sale_price' => null, 'stock_quantity' => 100, 'sold_quantity' => 100, 'product_id' => 7, 'image_url' => 'https://firebasestorage.googleapis.com/v0/b/hangy-storage.appspot.com/o/products%2Fnsm%2Fnsm-2.jpg?alt=media&token=c7b52f4b-10a3-41cf-842e-f17b867a2ebc', 'created_at' => now(), 'updated_at' => now()),
            array('name' => 'Vị Bạc Hà', 'real_price' => null, 'daily_price' => null, 'flash_sale_price' => null, 'stock_quantity' => 100, 'sold_quantity' => 100, 'product_id' => 7, 'image_url' => 'https://firebasestorage.googleapis.com/v0/b/hangy-storage.appspot.com/o/products%2Fnsm%2Fnsm-3.jpg?alt=media&token=52a0436f-953b-4f17-b220-160fcbe0ebe1', 'created_at' => now(), 'updated_at' => now()),
            array('name' => 'Vị Chanh Bạc Hà', 'real_price' => null, 'daily_price' => null, 'flash_sale_price' => null, 'stock_quantity' => 100, 'sold_quantity' => 100, 'product_id' => 8, 'image_url' => 'https://firebasestorage.googleapis.com/v0/b/hangy-storage.appspot.com/o/products%2Ftc%2Ftc-1.jpg?alt=media&token=c7dfe85a-1c57-4cf2-95ba-bdba0da757c0', 'created_at' => now(), 'updated_at' => now()),
            array('name' => 'Vị Bạc Hà', 'real_price' => null, 'daily_price' => null, 'flash_sale_price' => null, 'stock_quantity' => 100, 'sold_quantity' => 100, 'product_id' => 8, 'image_url' => 'https://firebasestorage.googleapis.com/v0/b/hangy-storage.appspot.com/o/products%2Ftc%2Ftc-2.jpg?alt=media&token=97d67040-52fa-48a1-b6c0-0426ded7a516', 'created_at' => now(), 'updated_at' => now()),
            array('name' => 'Vị Chanh Bạc Hà', 'real_price' => null, 'daily_price' => null, 'flash_sale_price' => null, 'stock_quantity' => 100, 'sold_quantity' => 100, 'product_id' => 8, 'image_url' => 'https://firebasestorage.googleapis.com/v0/b/hangy-storage.appspot.com/o/products%2Ftc%2Ftc-3.jpg?alt=media&token=998f68c9-6ff1-46a1-bda5-133832354a45', 'created_at' => now(), 'updated_at' => now()),
        );

        DB::table('sub_products')->insert($model);
    }
}
